// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAaoGEu4PBI_QbdzdXgwk0OFPI1uG69Fw',
    appId: '1:724766878438:web:5390a6279f983353482927',
    messagingSenderId: '724766878438',
    projectId: 'joylink-b31dd',
    authDomain: 'joylink-b31dd.firebaseapp.com',
    storageBucket: 'joylink-b31dd.appspot.com',
    measurementId: 'G-XHE1Z9S6BT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJ36gKF-RVZpjHP0Zf5Yrfkx4ID-6AbiU',
    appId: '1:724766878438:android:50cd6598432869b7482927',
    messagingSenderId: '724766878438',
    projectId: 'joylink-b31dd',
    storageBucket: 'joylink-b31dd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASWS0KLTCEWKZX61pBC7IVykfjRKnvQm8',
    appId: '1:724766878438:ios:6369926603908d11482927',
    messagingSenderId: '724766878438',
    projectId: 'joylink-b31dd',
    storageBucket: 'joylink-b31dd.appspot.com',
    iosBundleId: 'com.example.joylink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASWS0KLTCEWKZX61pBC7IVykfjRKnvQm8',
    appId: '1:724766878438:ios:6369926603908d11482927',
    messagingSenderId: '724766878438',
    projectId: 'joylink-b31dd',
    storageBucket: 'joylink-b31dd.appspot.com',
    iosBundleId: 'com.example.joylink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAaoGEu4PBI_QbdzdXgwk0OFPI1uG69Fw',
    appId: '1:724766878438:web:7c22566fc3e6c2ab482927',
    messagingSenderId: '724766878438',
    projectId: 'joylink-b31dd',
    authDomain: 'joylink-b31dd.firebaseapp.com',
    storageBucket: 'joylink-b31dd.appspot.com',
    measurementId: 'G-5WPJBRQFDW',
  );
}
